### ISSUE TITLE
Values "sw"/"se" of labelPosition seems to be inversed ?

### ISSUE THREAD

**Issue by JL2014** [dedalusj/cloudgram#64]
Hi,

If I use : generic.users Users [labelPosition="sw"];

Then the label appears on the right and not on the left !

w is for west, no ? on the left, no ?

Greetings, JL.

**Comment by dedalusj** [comment]
This should now be fixed. Sorry it took me so long to get to this.

**Comment by JL2014** [comment]
Thank you !
